name: Docs

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  test-recipes:
    name: Check Recipe Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm test:examples
  check-doc-folders:
    name: Check Nav & Folders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm test:docs
