name: 'Setup Docker'
inputs:
  password:
    description: 'Password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Docker
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.password }}

    - name: Docker info
      run: |
        docker info
      shell:
        bash
